export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const TEST_DISPATCH = 'TEST_DISPATCH';
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const CLEAR_ALL_PRODUCT  = 'CLEAR_ALL_PRODUCT';
